title: The Ardor Brio Company
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ardorbrio.com" # the base hostname & protocol for your site

destination: _live
keep_files: ['_live/css']
