# Site settings
title: DEV - Derek Moon
email: dmoon79@gmail.com
description: "The portfolio of Derek Moon, a Seattle based web developer specializing in Wordpress, HTML5, Javascript app"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title

# Custom settings
source: _source
destination: _public
sass_dir: _sass
highlighter: rouge
gems:
  - octopress-debugger

#Exclude Folders
exclude: ['node_modules','css', '_sass', 'Gruntfile.js', 'package.json']
keep_files: ['_public/css']

#Collection defined
collections:
  jobs:
    output: false
    permalink: /jobs/:path/
  projects:
    output: true
    permalink: /projects/:slug/
